### ISSUE TITLE
Pan.structure enum missing

### ISSUE THREAD

**Issue by abhritchie** [ANZSoilData/def-au-schema-json#128]
Search ontology and schema for pan structure enumeration.

May be missing, may be present but not properly linked.

From Stuart Spencer:
PanStructure (under Pans) has no enum.
We have these values against it…which match the yellow book Third Edition pg 195. (Comments at end from yellow book)
code_domain    code_value        code_desc
C_PAN_STRUCTURE        C             Concretionary   -- spheroidal concretions cemented together
C_PAN_STRUCTURE        L              Platy                      -- plate-like units cemented together
C_PAN_STRUCTURE        N             Nodular                -- nodules of irregular shape cemented together
C_PAN_STRUCTURE        R             Vermicular          -- worm-like structure and/or cavities 
C_PAN_STRUCTURE        S              Vesicular              -- Sponge like structure having large pores, which may or may not be filled with softer material
C_PAN_STRUCTURE        V             Massive               -- No recognisable structure

**Comment by meganrwong** [comment]
So far as I can see pan structure is linked in the ontology. I'll tag as question to follow up with you.

**Comment by meganrwong** [comment]
![image](https://github.com/ANZSoilData/def-au-schema-json/assets/49380601/cad1c0ef-2f22-4158-9d6f-c196f2c9b2c6)

**Comment by meganrwong** [comment]
schema issue - linked in ontology
