### ISSUE TITLE
Structure.ansisType vocabularies are not showing in MD docs.

### ISSUE THREAD

**Issue by abhritchie** [ANZSoilData/def-au-schema-json#129]

**Comment by abhritchie** [comment]
Also Substrate.geneticType.

**Comment by meganrwong** [comment]
so ansis:type only (sp:Pedality-type
 or sp:Artificial-aggregates-structure) 
to type exactly 1 ?

**Comment by meganrwong** [comment]
issue 2. 
For geneticType is this ansis:genesis? If so, already appears to be bound to enums within the schema eg subst:Rock-genesis-hardened-artificial - enums from table 37 in yellow book
