### ISSUE TITLE
Refactor ansis:SoilStrength to ansis:Consistence

### ISSUE THREAD

**Issue by abhritchie** [ANZSoilData/def-au-schema-json#133]
![image](https://github.com/ANZSoilData/def-au-schema-json/assets/9596562/905117a7-ac8c-4c4b-9b4f-1b767867a515)

**Comment by meganrwong** [comment]
![image](https://github.com/ANZSoilData/def-au-schema-json/assets/49380601/e8203a2f-0cbd-48cd-9c8d-6482a15d5fb6)

**Comment by meganrwong** [comment]
![image](https://github.com/ANZSoilData/def-au-schema-json/assets/49380601/2f3842c2-9965-4499-9618-a058f042bd1b)

**Comment by meganrwong** [comment]
Ontology - I can't see soil strength on Substrate so I think all is good

**Comment by meganrwong** [comment]
Is this asking for consistence as a property, with schema:rangeIncludes Consistence-strength, Consistence-stickiness? note we also have Strength - Seggregations-strength and Material-strength. And stickiness is a property with schema:rangeInslude Cosnstence-stickiness
