### ISSUE TITLE
check microRelief_gilgai cardinality

### ISSUE THREAD

**Issue by abhritchie** [ANZSoilData/def-au-schema-json#136]
From: Spencer, Stuart (A&F, Black Mountain) <Stuart.Spencer@csiro.au> 
Sent: Monday, 31 July 2023 5:29 PM
To: Wilson, Peter (A&F, Black Mountain) <Peter.Wilson@csiro.au>
Subject: MicroReliefs - JSON Output Schema

There are only two sites that have multiple GILGAI Microreliefs.
The new schema allows only one “Gilgai” MR (as per the discussion last week).
Given it’s too late to change the model, in these circumstances should the first one be used and the second ignored?

agency_code	proj_code	s_id	o_id	mr_no	mr_type	mr_prop_gilgai	mr_biotic_agent	mr_biotic_comp	mr_vertical_int	mr_horiz_int
704	ROWRA	117	1	1	M	NULL	NULL	NULL	0.3	5
704	ROWRA	117	1	2	N	NULL	NULL	NULL	NULL	NULL
899	Macquarie	261	1	1	N	NULL	NULL	NULL	0.2	20
899	Macquarie	261	1	2	N	NULL	NULL	NULL	0.5	30

M = "Melonhole gilgai"
N = "Normal gilgai"

Stuart 

---

From: Wilson, Peter (A&F, Black Mountain) <Peter.Wilson@csiro.au> 
Sent: Monday, 31 July 2023 5:43 PM
To: Spencer, Stuart (A&F, Black Mountain) <Stuart.Spencer@csiro.au>
Cc: Grealish, Gerard (A&F, Black Mountain) <Gerard.Grealish@csiro.au>; Searle, Ross (A&F, St. Lucia) <Ross.Searle@csiro.au>; Alistair Ritchie <RitchieA@landcareresearch.co.nz>
Subject: RE: MicroReliefs - JSON Output Schema

Hi Stuart

Interesting there are multiple gilgai (particularly in ROWRA given the other P Wilson involvement) - I recall our soil experts emphatically saying there should only be one type on a site. – guess that turns out to be opinion 😊
The Macquarie project records  different sizes, so they are obviously splitters not lumpers………

Yes, use the first record in each case.
Would be good if mr_prop_ was recorded, then we could make an educated guess about the dominant one
P

---

From: Searle, Ross (A&F, St. Lucia) <Ross.Searle@csiro.au> 
Sent: Monday, July 31, 2023 7:54 PM
To: Wilson, Peter (A&F, Black Mountain) <Peter.Wilson@csiro.au>; Spencer, Stuart (A&F, Black Mountain) <Stuart.Spencer@csiro.au>
Cc: Grealish, Gerard (A&F, Black Mountain) <Gerard.Grealish@csiro.au>; Alistair Ritchie <RitchieA@landcareresearch.co.nz>
Subject: RE: MicroReliefs - JSON Output Schema

Hmmm, I am not sure you can get both melonhole and normal gilgai within one site. They are similar but not the same – maybe they couldn’t decide which one it was

**Comment by abhritchie** [comment]
One

**Comment by meganrwong** [comment]
Noted, kept as 1 in ontology. I've noted this as a question for discussion - re where and how are these rules re carnality maintained into future
