### ISSUE TITLE
Update CoarseFragments enumerations

### ISSUE THREAD

**Issue by abhritchie** [ANZSoilData/def-au-schema-json#141]
Following discussion with Stuart et al, we should add the enum for substrate lithology as additional allowed values for surface and layer coarse fragments – page 142 – where CF lithology is different from either substrate, rock outcrop or both, then describe as per substrate lithology values Table 35 p214.

**Comment by abhritchie** [comment]
Added enums for substrate 'lithology - rock' and 'lithology - unconsolidated' to CoarseFragments lithology.

**Comment by meganrwong** [comment]
the ontology allows this
![image](https://github.com/ANZSoilData/def-au-schema-json/assets/49380601/11c798c1-b8a1-4b77-bf3d-1d191d83a54c)
