### ISSUE TITLE
modify definition of physical 

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-schema-json#68]

**Comment by abhritchie** [comment]
Have removed physical - discuss.

**Comment by meganrwong** [comment]
Leave in ontology for now - reasoning below - 
ontology has coded ansis:physical as a concept - observable property w def soil physical property
we also have ansis:chemical as a a concept  -observable property with def soil chemical property

Alone these are not very informative as properties.  At the moment we just use them with an example of property chemistry having some example sub properties (below). Can't hurt to keep them in ontology - may be useful once we decide how to /if we will maintain a properties ontology as external to the core where we could link off to rangeIncludes to external chemical and physical properties vocabs.
![image](https://github.com/ANZSoilData/def-au-schema-json/assets/49380601/ea0333e6-1266-4692-b72a-5f95bfeb776a)
