### ISSUE TITLE
Substrate - add substrateTexture with new enum

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-schema-json#89]

**Comment by abhritchie** [comment]
p207: Substrate Texture

**Comment by abhritchie** [comment]
Vocab was correct, but the name (Field Texture) is inconsistent with the Yellow Book.

**Comment by meganrwong** [comment]
change in ontology and YB enum vocabulary - Field-texture to Texture

**Comment by meganrwong** [comment]
![image](https://github.com/ANZSoilData/def-au-schema-json/assets/49380601/a59a4fc8-d27e-4d52-a294-7cc064c1b0b1)

**Comment by meganrwong** [comment]
change subst:Field-texture to subst:Substrate-texture
