### ISSUE TITLE
Substrate - search for substrate structure and mineral composition in ontology and schema

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-schema-json#90]

**Comment by abhritchie** [comment]
mineral composition = ansis:material. Property and enum existed but hadn't been linked to Substrate.

**Comment by abhritchie** [comment]
Added structure property and SubstrateStructure enum.

**Comment by meganrwong** [comment]
ontology - mineral composition seems fine
![image](https://github.com/ANZSoilData/def-au-schema-json/assets/49380601/89d38cc7-1f94-4e9b-afef-dfbad3fa1361)

**Comment by meganrwong** [comment]
ontology - ansis:substrate structure and enums seem fine
