### ISSUE TITLE
Substrate - search for substrate observation in yellow book for usedProcedure

### ISSUE THREAD

**Issue by meganrwong** [ANZSoilData/def-au-schema-json#91]

**Comment by abhritchie** [comment]
Currently linked to Profile Construction. @meganrwong - can you check the ontology first?

**Comment by abhritchie** [comment]
Profile construction + O

**Comment by abhritchie** [comment]
Yellow book p205-206

**Comment by abhritchie** [comment]
Created enum for http://anzsoil.org/def/au/asls/substrate/type-of-substrate-observation

**Comment by meganrwong** [comment]
It seems to be schema issue only.
The substrate has member Profiles,  and Profiles have the used procedure of Profile-construction, including link to enumerations for construction procedures.
